export * from './search.interface'
export * from './tv.interface'
export * from './movie.interface'
export * from './genre.interface'
export * from './auth.interface'
export * from './account.interface'
export * from './actors.interface'
